"""Initial migration

Revision ID: 6a853155c4b4
Revises: 
Create Date: 2023-05-16 16:15:44.674746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a853155c4b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('color',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('phone',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('brand_pk', sa.Integer(), nullable=True),
    sa.Column('color_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_pk'], ['brand.pk'], name='Brand'),
    sa.ForeignKeyConstraint(['color_pk'], ['color.pk'], name='Color'),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone')
    op.drop_table('color')
    op.drop_table('brand')
    # ### end Alembic commands ###
