"""empty message

Revision ID: ffd136aa1ab1
Revises: 6a853155c4b4
Create Date: 2023-06-22 12:39:15.780856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd136aa1ab1'
down_revision = '6a853155c4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('description',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_pk', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('Description', 'description', ['description_pk'], ['pk'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.drop_constraint('Description', type_='foreignkey')
        batch_op.drop_column('description_pk')

    op.drop_table('description')
    # ### end Alembic commands ###
